### ISSUE TITLE
shimming-toolbox.org returns error 404 page not found

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox.org#29]
When calling the website with shimming-tooolbox.org , the website displays an error. Possibly because there is not an index.md file.

**Comment by jcohenadad** [comment]
shouldn't the CNAME be updated? @alexfoias can you do it pls?

**Comment by po09i** [comment]
The gh-pages branch seems to be erased and built from scratch every time there is a push. I think the CNAME is created using this [line](https://github.com/shimming-toolbox/shimming-toolbox.org/blob/24d1113eb80d6f5e6a015eb0f60bb8cebf55c241/.github/workflows/main.yml#L28) in the workflow.

**Comment by kousu** [comment]
The problem was that the [Pages Source](https://help.github.com/en/github/working-with-github-pages/about-github-pages#publishing-sources-for-github-pages-sites) was set to `master` in https://github.com/shimming-toolbox/shimming-toolbox.org/settings. I've set it back to `gh-pages` and it's fixed now.

**Comment by kousu** [comment]
It doesn't matter if the CNAME file gets erased and remade; it's only read once each publish, it just has to be there on the right branch (either `master` or `gh-pages`, depending).

Note: the CNAME file is a different beast from the CNAME DNS record -- so @alexfoias doesn't need to do anything. The CNAME file is what I know of as a VirtualHost definition, which is rather the opposite (or complement) of a CNAME DNS record. They picked confusing terminology for that.

**Comment by po09i** [comment]
I'm still having the same issue, the first page I get when looking at the website is a 404 page not found.
<img width="1067" alt="Screen Shot 2020-06-17 at 00 14 43" src="https://user-images.githubusercontent.com/47249340/84854410-8e906280-b02f-11ea-81d0-66ba453de4ed.png">

To me it makes sense since we don't have an index.md file in the folder anymore so it does not have a first page to link to...

**Comment by alexfoias** [comment]
the CNAME & setup on namecheap seem to do the job. I think is more a problem of page content.

**Comment by jcohenadad** [comment]
> To me it makes sense since we don't have an index.md file in the folder anymore so it does not have a first page to link to...

that makes sense indeed.. how come we don't have an index.md anymore? are we ready to do the switch to the new repository shimming-toolbox/shimming-toolbox?

**Comment by po09i** [comment]
Website has been switched to the shimming-toolbox repo. The website's first page as well. This can be closed.
